import { Keyboard } from 'grammy'

export const editExpenseKeyboard = new Keyboard()
  .text('Ask 🎙️')
  .row()
  .text('Just add ➕')
  .row()
  .text('Organize 📍')
  .row()
  .text('Cancel ❌')
  .resized()
  .oneTime()

export const descriptionKeyboard = new Keyboard()
  .text('Describe')
  .row()
  .text('Autogenerate')
  .row()
  .resized()
  .oneTime()
